import { createContext, useContext, useState, type ReactNode } from "react";

type Language = "en" | "pt";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    "nav.features": "Features",
    "nav.examples": "Examples",
    "nav.pricing": "Pricing",
    "nav.getStarted": "Get Started",

    // Hero Section
    "hero.badge": "AI-Powered Profile Generation",
    "hero.title": "Generate Premium",
    "hero.titleHighlight": "Professional Profiles",
    "hero.subtitle":
      "Create stunning, developer-centric professional profiles that serve as powerful digital business cards. Perfect for recruiters, hiring managers, and professional collaborators.",
    "hero.generateProfile": "Generate Your Profile",
    "hero.viewExamples": "View Examples",
    "hero.stats.profiles": "Profiles Generated",
    "hero.stats.success": "Success Rate",
    "hero.stats.rating": "User Rating",

    // Profile Preview
    "preview.name": "Alex Rodriguez",
    "preview.title": "Senior Product Designer",
    "preview.bio":
      "Passionate designer crafting digital experiences that blend creativity with user-centered thinking.",
    "preview.email": "Email",
    "preview.phone": "Phone",
    "preview.linkedin": "LinkedIn",
    "preview.portfolio": "Portfolio",
    "preview.keyProjects": "Key Projects",

    // Features Section
    "features.title": "Everything You Need for a",
    "features.titleHighlight": "Professional Presence",
    "features.subtitle":
      "Our AI-powered platform generates comprehensive professional profiles that showcase your skills, experience, and projects in a clean, developer-centric design.",
    "features.aiPowered.title": "AI-Powered Generation",
    "features.aiPowered.desc":
      "Advanced AI analyzes your input to create compelling copy and optimal layout structures automatically.",
    "features.recruiterOptimized.title": "Recruiter-Optimized",
    "features.recruiterOptimized.desc":
      "Designed specifically for hiring managers and recruiters to quickly assess your value and expertise.",
    "features.completeProfiles.title": "Complete Profiles",
    "features.completeProfiles.desc":
      "Includes contact info, project showcases, experience timeline, skills, and education sections.",
    "features.premiumDesign.title": "Premium Design",
    "features.premiumDesign.desc":
      "Clean, minimalist aesthetic inspired by top developer tools like Replicate.com and GitHub.",
    "features.instantExport.title": "Instant Export",
    "features.instantExport.desc":
      "Generate and export your profile in multiple formats: PDF, HTML, or shareable link.",
    "features.mobileResponsive.title": "Mobile Responsive",
    "features.mobileResponsive.desc":
      "Profiles look perfect on all devices, ensuring accessibility for all viewers.",

    // Examples Section
    "examples.title": "See What's Possible",
    "examples.subtitle":
      "Real profiles generated by our platform for professionals across different industries.",

    // CTA Section
    "cta.title": "Ready to Create Your",
    "cta.titleHighlight": "Professional Profile?",
    "cta.subtitle":
      "Join thousands of professionals who've elevated their online presence with our AI-powered profile generator.",
    "cta.generateNow": "Generate Profile Now",
    "cta.viewPricing": "View Pricing",
    "cta.noCard": "No credit card required",
    "cta.generate60s": "Generate in 60 seconds",
    "cta.exportAnywhere": "Export anywhere",

    // Footer
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.support": "Support",
    "footer.copyright": "© 2024 ProfileGen. All rights reserved.",
  },
  pt: {
    // Navigation
    "nav.features": "Recursos",
    "nav.examples": "Exemplos",
    "nav.pricing": "Preços",
    "nav.getStarted": "Começar",

    // Hero Section
    "hero.badge": "Geração de Perfil com IA",
    "hero.title": "Gere Perfis",
    "hero.titleHighlight": "Profissionais Premium",
    "hero.subtitle":
      "Crie perfis profissionais impressionantes e centrados no desenvolvedor que servem como cartões de visita digitais poderosos. Perfeito para recrutadores, gerentes de contratação e colaboradores profissionais.",
    "hero.generateProfile": "Gerar Seu Perfil",
    "hero.viewExamples": "Ver Exemplos",
    "hero.stats.profiles": "Perfis Gerados",
    "hero.stats.success": "Taxa de Sucesso",
    "hero.stats.rating": "Avaliação",

    // Profile Preview
    "preview.name": "Alex Rodriguez",
    "preview.title": "Designer de Produto Sênior",
    "preview.bio":
      "Designer apaixonado criando experiências digitais que combinam criatividade com pensamento centrado no usuário.",
    "preview.email": "Email",
    "preview.phone": "Telefone",
    "preview.linkedin": "LinkedIn",
    "preview.portfolio": "Portfólio",
    "preview.keyProjects": "Projetos Principais",

    // Features Section
    "features.title": "Tudo o Que Você Precisa para uma",
    "features.titleHighlight": "Presença Profissional",
    "features.subtitle":
      "Nossa plataforma alimentada por IA gera perfis profissionais abrangentes que mostram suas habilidades, experiência e projetos em um design limpo e centrado no desenvolvedor.",
    "features.aiPowered.title": "Geração com IA",
    "features.aiPowered.desc":
      "IA avançada analisa sua entrada para criar textos convincentes e estruturas de layout ideais automaticamente.",
    "features.recruiterOptimized.title": "Otimizado para Recrutadores",
    "features.recruiterOptimized.desc":
      "Projetado especificamente para gerentes de contratação e recrutadores avaliarem rapidamente seu valor e expertise.",
    "features.completeProfiles.title": "Perfis Completos",
    "features.completeProfiles.desc":
      "Inclui informações de contato, showcases de projetos, linha do tempo de experiência, habilidades e seções de educação.",
    "features.premiumDesign.title": "Design Premium",
    "features.premiumDesign.desc":
      "Estética limpa e minimalista inspirada nas melhores ferramentas de desenvolvedor como Replicate.com e GitHub.",
    "features.instantExport.title": "Exportação Instantânea",
    "features.instantExport.desc":
      "Gere e exporte seu perfil em múltiplos formatos: PDF, HTML ou link compartilhável.",
    "features.mobileResponsive.title": "Responsivo Mobile",
    "features.mobileResponsive.desc":
      "Perfis ficam perfeitos em todos os dispositivos, garantindo acessibilidade para todos os visualizadores.",

    // Examples Section
    "examples.title": "Veja o Que é Possível",
    "examples.subtitle":
      "Perfis reais gerados por nossa plataforma para profissionais de diferentes indústrias.",

    // CTA Section
    "cta.title": "Pronto para Criar Seu",
    "cta.titleHighlight": "Perfil Profissional?",
    "cta.subtitle":
      "Junte-se a milhares de profissionais que elevaram sua presença online com nosso gerador de perfil alimentado por IA.",
    "cta.generateNow": "Gerar Perfil Agora",
    "cta.viewPricing": "Ver Preços",
    "cta.noCard": "Não é necessário cartão de crédito",
    "cta.generate60s": "Gere em 60 segundos",
    "cta.exportAnywhere": "Exporte para qualquer lugar",

    // Footer
    "footer.privacy": "Privacidade",
    "footer.terms": "Termos",
    "footer.support": "Suporte",
    "footer.copyright": "© 2024 ProfileGen. Todos os direitos reservados.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return (
      translations[language][key as keyof (typeof translations)["en"]] || key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
